spreadsheet_id = ""

emails_proprietarios = [
    "tesouraria.rj@gmail.com",
    "atfontenelle@gmail.com",
    "daysefontenelle@gmail.com",
]

gcp_service_account = '{"type": "service_account", "project_id": "SEU_PROJECT_ID", "private_key_id": "SEU_PRIVATE_KEY_ID", "private_key": "-----BEGIN PRIVATE KEY-----\nSUA_PRIVATE_KEY_AQUI\n-----END PRIVATE KEY-----\n", "client_email": "sua-service-account@seu-projeto.iam.gserviceaccount.com", "client_id": "SEU_CLIENT_ID", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sua-service-account%40seu-projeto.iam.gserviceaccount.com", "universe_domain": "googleapis.com"}'

[gestores]
users = [
    {login = "gestor1", senha = "senha_segura_1"},
    {login = "gestor2", senha = "senha_segura_2"},
    {login = "gestor3", senha = "senha_segura_3"},
    {login = "gestor4", senha = "senha_segura_4"},
    {login = "gestor5", senha = "senha_segura_5"},
]